version: '3.3'
 
services:
  docker-node:
    build: ./node
    image: docker-node:prod
    container_name: node-prod
    volumes:
      - ./node:/node
      - /node/node_modules
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
  docker-nginx:
    build: ./nginx
    image: docker-nginx:prod
    container_name: nginx-prod
    ports:
      - 8081:80
    links:
      - docker-node # link "docker-nginx" to "docker-node"
    environment:
      - NGINX_PORT=80
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf