version: '3.3'
 
services:
  node-express:
    build: ./docker_test
    image: docker-node:dev
    container_name: node-dev5
    volumes:
      - ./docker_test:/docker_test
      - /docker_test/node_modules
    ports:
      - 3000:3000
  nginx:
    build: ./nginx_test
    image: nginx:0.0.1
    container_name: nginx-dev
    ports:
      - 8081:80
    links:
      - node-express # link "nginx" to "node-express"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    volumes:
      - ./nginx_test/html:/usr/share/nginx/html
      - ./nginx_test/default.conf:/etc/nginx/conf.d/default.conf